import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  return [
    // Core Pages - Priority 1.0
    {
      url: "https://www.umangengineering.com",
      lastModified,
      changeFrequency: "weekly",
      priority: 1,
    },

    // Main Pages - Priority 0.8
    {
      url: "https://www.umangengineering.com/about-us",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/product",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/news-exhibition",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/distributor",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/customize",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/resources",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/free-quote",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/case-studies",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/white-papers",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/leadership-team",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/mission-vision",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/sustainability",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/encapsulation-technology",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/our-other-brands",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/catalogue-brochures",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/ingredient-books",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/media",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/blogs",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.u.com/faqs",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/contact-us",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/formulations",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },

    // Legal Pages - Priority 0.8
    {
      url: "https://www.umangengineering.com/terms-conditions",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/privacy-policy",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/cookies-policy",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.8,
    },

    // Product Single Pages - Priority 0.9
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-creatine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-caffeine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-co-enzyme-q10-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-melatonin-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-nadh-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-nmn-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-hyaluronic-acid-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-cysteine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-citric-acid-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-gamma-amino-butyric-acid-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-alpha-arbutin-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-tyrosine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-lysine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-palmitoyl-tripeptide-5-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-yohimbine-hcl-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-mushroom-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-curcumin-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-green-tea-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-marine-collagen-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-pancreatin-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-papain-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-a-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-b1-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-b2-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-b3-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-b5-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-b6-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-b7-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-b9-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-c-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-d2-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-d3-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-k1-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-k2-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-e-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-astaxanthin-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-beta-carotene-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-coq10-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-lutein-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-lycopene-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-mixed-carotene-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-zeaxanthin-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-boron-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-calcium-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-copper-sulphate-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-ferrous-ascorbate-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-dried-ferrous-sulphate-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-magnesium-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-selenium-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-zinc-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-chromium-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-manganese-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-phosphorous-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-iodine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-potassium-chloride-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-arginine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-branched-chain-amino-acid-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-dl-metheonine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-histidine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-l-glutamine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-l-leucine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-l-threonine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-l-valine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-phenylalanine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-tryptophan-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-l-carnitine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-l-theanine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-alovera-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-acerola-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-ashwagandha-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-astragalus-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-apple-cider-vinegar-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-basil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-berberine-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-berry-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-black-cohosh-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-black-musli-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-boswellia-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-brahmi-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-sea-buckthorn-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-capsaicin-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-chamomile-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-curry-leaf-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-dandelion-leaf-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-dong-quai-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-echinacea-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-slippery-elm-bark-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-fennel-extract-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-fenugreek-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-garcinia-cambogia-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-garlic-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-ginkgo-biloba-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-ginger-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-ginseng-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-guarana-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-hibiscus-leaf-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-inulin-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-kava-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-lavender-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-lemon-balm-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-maca-root-powder-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-moringa-leaf-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-milk-thistle-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-mucuna-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-neem-leaf-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-nettle-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-onion-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-saw-palmetto-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-parsley-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-passion-flower-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-pepper-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-rodhiola-rosea-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-rosemary-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-saffron-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-sage-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-seaweed-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-senna-leaves-extract-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-shilajit-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-st-johns-wort-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-spirulina-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-thyme-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-valerian-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-white-willow-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-mint-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-star-anise-oil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-caraway-seed-oil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-cinnamon-oil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-nutmeg-oil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-thyme-oil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-cardamom-oil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-parsley-oil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-cumin-oil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-dha-oil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-eucalyptus-oil-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.umangengineering.com/product-single/encapsulated-vitamin-b12-beadlets",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
    url: "https://www.umangengineering.com/product-single/encapsulated-apple-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    url: "https://www.umangengineering.com/product-single/encapsulated-bamboo-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    url: "https://www.umangengineering.com/product-single/encapsulated-beetroot-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    url: "https://www.umangengineering.com/product-single/encapsulated-carrot-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    url: "https://www.umangengineering.com/product-single/encapsulated-citrus-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    url: "https://www.umangengineering.com/product-single/encapsulated-inulin-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    url: "https://www.umangengineering.com/product-single/encapsulated-pea-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    url: "https://www.umangengineering.com/product-single/encapsulated-potato-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    url: "https://www.umangengineering.com/product-single/encapsulated-psyllium-seed-husks-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    url: "https://www.umangengineering.com/product-single/encapsulated-soybean-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    url: "https://www.umangengineering.com/product-single/encapsulated-fruit-or-vegetable-pulp-fiber-beadlets",
    lastModified,
    changeFrequency: "weekly",
    priority: 0.9,
  },

    // Product Pages - Priority 0.8
   
    
    {
      url: "https://www.umangengineering.com/products/vitaspheres",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/products/minospheres",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/products/caratospheres",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/products/actispheres",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/products/botanispheres",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/products/aminospheres",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/products/oilspheres",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/products/fibrespheres",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    
    // Sustainability Pages - Priority 0.8
    {
      url: "https://www.umangengineering.com/planting-for-every-life",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/green-visitor-program",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/ai-driven-sustainability",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.umangengineering.com/zero-waste-manufacturing",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },

    // Secondary Pages - Priority 0.64
    {
      url: "https://www.umangengineering.com/capabilities",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/information",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/downloads",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/company",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/videos",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/magazine",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.64,
    },

    // News & Exhibition Pages - Priority 0.64
    {
      url: "https://www.umangengineering.com/news-exhibitions/vitafoods-europe-2025",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/in-cosmetics-amsterdam-2025",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/pharmaconex-2024",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/cosmohome-tech-expo-2024",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/cospack-cosmetic-packaging-expo-2024",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/arab-pharma-manufactures-2024",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/in-cosmetics-asia-2023",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/cphi-europe-2019",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/cosmotech-expo-2019",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/medi-pharma-expo-vietnam-2018",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/incosmetic-global-amsterdam-2019",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/cphi-china-shanghai-2019",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/fce-pharma-sao-paulo-brazil-2019",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/incosmetic-global-paris-2019",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/hpci-india-2019",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/pchi-china-2019",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/duphat-exhibition-dubai-2019",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.umangengineering.com/news-exhibitions/hpci-exhibition-india-2018",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.64,
    },

    // Services Pages - Priority 0.51
    {
      url: "https://www.umangengineering.com/bulk-contract-manufacturing",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/quality-control",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/co-development-project",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/manufacturing-site-transfer-projects",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/white-labelling-co-branding",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/certificates",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/flyers",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/services",
      lastModified,
      changeFrequency: "monthly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/careers",
      lastModified,
      changeFrequency: "weekly",
      priority: 0.51,
    },

    // Video Pages - Priority 0.51
    {
      url: "https://www.umangengineering.com/videos-single/glow-with-the-power-of-turmeric",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/micro-encapsulated-ingredients-for-nutraceuticals-umang-global-group-pvt-ltd",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/capsicum-without-the-burn-meet-capsiencap-the-smarter-way-to-deliver-heat",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/aminospheres-nutrition-made-smarter-nutraceuticals-umang-global-group",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/why-nutrients-lose-their-power-before-you-absorb-them",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/l-leucine-beadlets-precision-delivery-in-action",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/want-brahmi-beadlets-that-deliver-not-just-promise",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/actispheres-precision-encapsulation-for-wellness-nutraceuticals-umang-global-group",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/struggling-to-sleep-this-tiny-beadlet-changed-everything",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/boost-your-wellness-with-botanispheres-ashwagandha-nutraceuticals-umang-global-group",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/the-growing-impact-of-carotenoids-on-human-health-nutraceuticals-umang-global-group",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/essential-vitamins-the-key-to-growth-and-vital-functioning-nutraceuticals-umang%20global%20group",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/shilajit-beadlets-the-future-of-ancient-wellness-encapsulation-innovation-in-nutraceuticals",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/minerals-small-nutrients-big-impact-on-your-health-nutraceuticals-umang-global-group",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/encapsulated-capsaicin-metabolism-and-weight-management",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/micro-encapsulated-heart-care-for-nutraceuticals-umang-global-group-pvt-ltd",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/nutraceuticals-for-sports-nutrition-fuel-your-performance",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/micro-encapsulated-gut-care-for-nutraceuticals-umang-global-group-pvt-ltd",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/enhance-your-well-being-by-nourishing-your-body-with-nutraceuticals",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/gut-care-nutraceuticals-support-your-digestive-health-naturally",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/taste-masking-making-medicines-more-palatable-for-all-nutraceuticals-umang-global-group",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/nutraceuticals-for-weight-management-your-partner-in-achieving-a-healthier-lifestyle",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/boost-your-immunity-with-advanced-nutraceuticals",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/l-arginine-beadlets-technolog-taste-masked-and-custom-release-solutions",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/naturally-support-your-mind-with-nutraceuticals-for-mental-wellbeing",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
    {
      url: "https://www.umangengineering.com/videos-single/nutraceuticals-for-men-and-women-unlock-your-health-potential",
      lastModified,
      changeFrequency: "yearly",
      priority: 0.51,
    },
  ];
}